stages:
  - build
  - deploy

variables:
  NODE_VERSION: '20'
  NPM_CACHE_FOLDER: "$CI_PROJECT_DIR/.npm"

.default:
  image: node:${NODE_VERSION}
  cache:
    key: "npm-cache"
    paths:
      - .npm/
      - node_modules/
  before_script:
    - npm ci

build:prod:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist/

vercel:deploy:prod:
  stage: deploy
  needs: ["build:prod"]
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - npm i -g vercel@latest
    - vercel pull --yes --environment=production --token "$VERCEL_TOKEN"
    - vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"
  variables:
    VERCEL_TOKEN: "$VERCEL_TOKEN"
    VERCEL_ORG_ID: "$VERCEL_ORG_ID"
    VERCEL_PROJECT_ID: "$VERCEL_PROJECT_ID"

